import {
  IconBrandRust,
  IconBarrel,
  IconBeer,
  IconBottle,
  IconBinary,
  IconTerminal2,
  IconPackages,
  IconBrandGit,
  IconBrandApple,
  IconBrandPython,
  IconScript,
  IconBrandGolang,
  IconBrandNodejs,
  IconWorldCode,
  IconBook,
  IconEdit,
  IconTrash,
  IconReload,
  IconDeviceFloppy,
  IconX

} from '@tabler/icons-react';

export const ICON = {
  cargo: IconBrandRust,
  taps: IconBarrel,
  brews: IconBeer,
  casks: IconBarrel,
  binaries: IconBinary,
  commands: IconTerminal2,
  gem: IconPackages,
  git: IconBrandGit,
  mas: IconBrandApple,
  pip: IconBrandPython,
  pipx: IconBrandPython,
  scripts: IconScript,
  go: IconBrandGolang,
  node: IconBrandNodejs,
  allApps: IconWorldCode,
  detail: IconBook,
  edit: IconEdit,
  remove: IconTrash,
  startOver: IconReload,
  save: IconDeviceFloppy,
  close: IconX
};