#version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - db_data:/var/db-data
    command: >
      sh -c "test -f /var/db-data/dev.db && pwd && ls -la && exec node index.js"

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
volumes:
  db_data: