export const ROUTES = {
  software: "/software",
  softwareNotDone: "/softwareNotDone",
  filterBy: "/filterBy",
  getApp: "/getApp",
  updateNode: "/updateNode",
  addNode: "/addNode",
  deleteNode: "/deleteNode",
  getAllTags: "/getAllTags",
  getTagsByAppId: "/getTagsByAppId",
  addAppTags: "/addAppTags",
  deleteAppTag: "/deleteAppTag",
  download: "/download",
  filteredDownload: "/filtered-download",
  softwareGroups: "/software-groups",
  groups: "/groups",
  groupApps: "/group-apps",
  appGroups: "/app-groups",
  getGroupById: "/getGroupById",
  addAppToGroup: "/addAppToGroup",
  removeAppFromGroup: "/removeAppFromGroup",
  groupedApps: "/groupedApps",
  updateAllowedTags: "/updateAllowedTags",
};