export const APP_FORM = {
	formPartOne: [
		{ name: "name", label: "Name", trapFocus: true },
		{ name: "key", label: "Key" },
		{ name: "bin", label: "Executable" },
		{ name: "short", label: "Short desc" },
		{ name: "home", label: "Homepage" },
		{ name: "docs", label: "Documentation" },
		{ name: "github", label: "Github" },
	],
	formPartTwo: [
		{ name: "whalebrew", label: "Whalebrew" },
		{ name: "apt", label: "Apt" },
		{ name: "brew", label: "Homebrew" },
		{ name: "cask", label: "Homebrew cask" },
		{ name: "cargo", label: "Cargo" },
		{ name: "npm", label: "NPM" },
		{ name: "pip", label: "Pip" },
		{ name: "pipx", label: "Pipx" },
		{ name: "gem", label: "Gem" },
		{ name: "script", label: "Script" },
		{ name: "choco", label: "Chocolatey" },
		{ name: "scoop", label: "Scoop" },
		{ name: "winget", label: "Winget" },
		{ name: "pkgdarwin", label: "Pkg-Darwin" },
		{ name: "ansible", label: "Ansible" },
		{ name: "binary", label: "Binary" },
		{ name: "yay", label: "Yay" },
		{ name: "appstore", label: "AppStore" },
		{ name: "pacman", label: "Pacman" },
		{ name: "port", label: "MacPort" },
	],
};

export const EMPTY_APP2 = {
	name: null,
	key: null,
	desc: null,
	bin: null,
	short: null,
	home: null,
	docs: null,
	github: null,
	whalebrew: null,
	apt: null,
	brew: null,
	cask: null,
	cargo: null,
	npm: null,
	pip: null,
	pipx: null,
	gem: null,
	script: null,
	choco: null,
	scoop: null,
	winget: null,
	pkgdarwin: null,
	ansible: null,
	binary: null,
	yay: null,
	appstore: null,
	pacman: null,
	port: null,
	tags: null,
};

export const EMPTY_APP = {
	name: null,
	key: null,
	desc: null,
	bin: null,
	short: null,
	home: null,
	docs: null,
	github: null,
	whalebrew: null,
	apt: null,
	brew: null,
	cask: null,
	cargo: null,
	npm: null,
	pip: null,
	pipx: null,
	gem: null,
	script: null,
	choco: null,
	scoop: null,
	winget: null,
	pkgdarwin: null,
	ansible: null,
	binary: null,
	yay: null,
	appstore: null,
	pacman: null,
	port: null,
	tags: null,
};
