export const APP_FORM = {
	formPartOne: [
		{ name: "name", label: "Name" },
		{ name: "key", label: "Key" },
		{ name: "bin", label: "Executable" },
		{ name: "short", label: "Short desc" },
		{ name: "home", label: "Homepage" },
		{ name: "docs", label: "Documentation" },
		{ name: "github", label: "Github" },
	],
	formPartTwo: [
		{ name: "whalebrew", label: "Whalebrew" },
		{ name: "apt", label: "Apt" },
		{ name: "brew", label: "Homebrew" },
		{ name: "cask", label: "Homebrew cask" },
		{ name: "cargo", label: "Cargo" },
		{ name: "npm", label: "NPM" },
		{ name: "pip", label: "Pip" },
		{ name: "pipx", label: "Pipx" },
		{ name: "gem", label: "Gem" },
		{ name: "script", label: "Script" },
		{ name: "choco", label: "Chocolatey" },
		{ name: "scoop", label: "Scoop" },
		{ name: "winget", label: "Winget" },
		{ name: "pkgdarwin", label: "Pkg-Darwin" },
		{ name: "ansible", label: "Ansible" },
		{ name: "binary", label: "Binary" },
		{ name: "yay", label: "Yay" },
		{ name: "appstore", label: "AppStore" },
		{ name: "pacman", label: "Pacman" },
		{ name: "port", label: "MacPort" },
	],
};

export const EMPTY_APP = {
	name: "",
	key: "",
	desc: "",
	bin: "",
	short: "",
	home: "",
	docs: "",
	github: "",
	whalebrew: "",
	apt: "",
	brew: "",
	cask: "",
	cargo: "",
	npm: "",
	pip: "",
	pipx: "",
	gem: "",
	script: "",
	choco: "",
	scoop: "",
	winget: "",
	pkgdarwin: "",
	ansible: "",
	binary: "",
	yay: "",
	appstore: "",
	pacman: "",
	port: "",
};
