export const appModelFieldTypes = {
	id: "id",
	name: "name",
	key: "key",
	desc: "desc",
	bin: "bin",
	short: "desc",
	home: "url",
	docs: "url",
	github: "url",
	whalebrew: "installer",
	apt: "installer",
	brew: "installer",
	cask: "installer",
	cargo: "installer",
	npm: "installer",
	pip: "installer",
	pipx: "installer",
	gem: "installer",
	script: "installer",
	choco: "installer",
	scoop: "installer",
	winget: "installer",
	pkgdarwin: "installer",
	ansible: "installer",
	binary: "installer",
	yay: "installer",
	appstore: "installer",
	pacman: "installer",
	port: "installer",
	tags: "tags",
};

export const appModelInstallerFields = [
	"whalebrew",
	"apt",
	"brew",
	"cask",
	"cargo",
	"npm",
	"pip",
	"pipx",
	"gem",
	"script",
	"choco",
	"scoop",
	"winget",
	"pkgdarwin",
	"ansible",
	"binary",
	"yay",
	"appstore",
	"pacman",
	"port",
];

export const appViewModel = {
	id: null,
	name: null,
	hasInstallers: null,
	edited: null,
	key: null,
	desc: null,
	bin: null,
	short: null,
	home: null,
	docs: null,
	github: null,
	whalebrew: null,
	apt: null,
	brew: null,
	cask: null,
	cargo: null,
	npm: null,
	pip: null,
	pipx: null,
	gem: null,
	script: null,
	choco: null,
	scoop: null,
	winget: null,
	pkgdarwin: null,
	ansible: null,
	binary: null,
	yay: null,
	appstore: null,
	pacman: null,
	port: null,
	tags: null,
};
